// frontend/src/App.tsx
import { useEffect, useState } from "react";
import { Editor } from "./Editor";
import { Events } from "@wailsio/runtime";
import { TagsService } from "../bindings/jot/internal/tags";
import { NoteService } from "../bindings/jot/internal/note";

function preventAlt(e: KeyboardEvent) {
  if (e.key === "Alt") {
    e.preventDefault;
  }
}

function App() {
  const [tags, setTags] = useState<string[]>([]);

  useEffect(() => {
    const onFocusIn = (e: FocusEvent) => {
      const target = e.target as Element;
      if (!target.closest("[data-focus-allowed]")) {
        (e.relatedTarget as HTMLElement)?.focus();
      }
    };
    document.addEventListener("focusin", onFocusIn);
    return () => document.removeEventListener("focusin", onFocusIn);
  }, []);

  useEffect(() => {
    TagsService.GetTags().then((cached) => {
      if (cached?.length) setTags(cached);
    });

    TagsService.ScanTags();

    const unsub = Events.On("tags-ready", (e) => {
      setTags(e.data as string[]);
    });

    window.addEventListener("keydown", preventAlt);
    window.addEventListener("keyup", preventAlt);

    return () => {
      window.removeEventListener("keydown", preventAlt);
      window.removeEventListener("keyup", preventAlt);
      unsub();
    };
  }, []);

  return (
    <Editor
      initialValue=""
      onSave={(val) =>
        NoteService.SaveNote(val).catch((err: any) =>
          console.error("SaveNote:", err),
        )
      }
      onDiscard={() => NoteService.ResetCurrNotePath()}
      tags={tags}
    />
  );
}

export default App;

// frontend/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { Events } from "@wailsio/runtime";
import { TagsService } from "../bindings/jot/internal/tags";
import Editor from "./Editor.vue";
import { NoteService } from "../bindings/jot/internal/note";

let tagsReadyEvent: () => void;

function preventAlt(e: KeyboardEvent) {
  if (e.key === "Alt") {
    e.preventDefault();
  }
}

const isFocusAllowed = (e: FocusEvent) => {
  const target = e.target as Element;
  if (!target.closest("[data-focus-allowed]")) {
    (e.relatedTarget as HTMLElement)?.focus();
  }
};

const tags = ref<string[]>([]);

onMounted(async () => {
  document.addEventListener("focusin", isFocusAllowed);

  tags.value = await TagsService.GetTags();
  TagsService.ScanTags();

  tagsReadyEvent = Events.On("tags-ready", (e) => {
    tags.value = e.data;
  });

  window.addEventListener("keyup", preventAlt);
  window.addEventListener("keydown", preventAlt);
});

onUnmounted(() => {
  document.removeEventListener("focusin", isFocusAllowed);
  window.removeEventListener("keyup", preventAlt);
  window.removeEventListener("keydown", preventAlt);
  tagsReadyEvent();
});

const onSave = (text: string) => {
  NoteService.SaveNote(text).catch((err: any) =>
    console.error("SaveNote:", err),
  );
};

const onNew = () => {
  NoteService.ResetCurrNotePath();
};
</script>

<template>
  <Editor :tags v-on:new="onNew" v-on:save="onSave" />
</template>

<style module>
@import "./reset.css";
</style>
